.read lab12.sql

CREATE TABLE fa16favnum AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE fa16favpets AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE sp17favpets AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE sp17dragon AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE sp17alldragons AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE TABLE obedienceimage AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";

CREATE TABLE smallest_int_count AS
  select "REPLACE THIS LINE WITH YOUR SOLUTION";
